import { sendEmailVerification } from "firebase/auth";
import { usersAPI } from "@/lib/api";

/** Toast copy for a requestVerificationEmail result. */
export function verificationToast(result) {
  if (result?.alreadyVerified) return { kind: "success", text: "Your email is already verified." };
  if (result?.recentlySent || result?.tooMany) return { kind: "message", text: "A link went out moments ago — check your inbox and spam before requesting another." };
  return { kind: "success", text: "Verification link sent" };
}

/**
 * Ask for a verification email (KB 28 M1). Ours first — generated by the backend and sent from our
 * domain with our layout — and Firebase's own sender only if ours reports it couldn't deliver.
 * Resolves with the backend's answer; throws only when both routes fail.
 */
export async function requestVerificationEmail(user, redirect = "/home") {
  const url = `${window.location.origin}/verify-email?redirect=${encodeURIComponent(redirect)}`;
  try {
    const { data } = await usersAPI.sendVerificationEmail(url);
    // tooMany: Firebase already issued a link for this account moments ago — its own sender is limited the same way, so don't retry there.
    if (data?.sent || data?.recentlySent || data?.alreadyVerified || data?.tooMany) return data;
  } catch {
    /* backend unreachable or refused — fall through to Firebase's sender */
  }
  await sendEmailVerification(user, { url });
  return { sent: true, fallback: true };
}
